version: "3.8"

services:
  backend:
    container_name: "citibike-system"
    build:
      context: ./citibike-system-data
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - citibike-network

  frontend:
    container_name: react-frontend
    build:
      context: ./citibike-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - citibike-network

networks:
  citibike-network:
    driver: bridge
