version: "3.8"

services:
  backend:
    build:
      context: ./citibike-system-data
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=http://localhost:5173
    networks:
      - citibike-network

  frontend:
    build:
      context: ./citibike-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - citibike-network

networks:
  citibike-network:
    driver: bridge
